config/routes.rb
BlogLec::Application.routes.draw do
  devise_for :users

  resources :posts do
    resources :comments
  end

  root 'posts#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  has_one :user
  validates_presence_of :post_id
  validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates_presence_of :title
  validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  '''
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    puts @comment.to_yaml
    puts @post.to_yaml
  end
  '''

  # GET /comments/1/edit
  def edit
    @post = Post.find(params[:post_id])
    @comment
    puts "Editing a comment for:"
    puts "Comment #{@comment.id}"
    puts "Post: #{@post.id}"
    
    # NEED TO DO USER ID CHECKS    
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(@post), notice: 'Comment was sucessfully updated.' }
      end    
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    # Added, to the get proper post id
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
        format.js #do something
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js #do something
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update

    if @comment.user_id != current_user.id
      @message = "You cannot update another user's comment."
      redirect_to @post, notice: @message
      return
    end

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @post, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy

    @post = Post.find(params[:post_id])    

    if @comment.user_id != current_user.id
      @message = "You cannot delete another user's comment."
      redirect_to @post, notice: @message
      return
    end
 

    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @post }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      #params.require(:comment).permit(:post_id, :body)
      params.require(:comment).permit(:post_id, :body, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @user = current_user
    @post.user_id = @user.id
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
        # Added, since we are now doing REMOTE (see hmtl.erb files)
        #format.js {} #do something
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        #format.js {} #do something
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.user_id != current_user.id
      @message = "You cannot update another user's post."
      redirect_to @post, notice: @message
      return
    end
    puts "USER OK TO EDIT POST"

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy

    if @post.user_id != current_user.id
      @message = "You cannot delete another user's post."
      redirect_to @post, notice: @message
      return
    end
    puts "USER OK TO DELETE POST"

    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      #params.require(:post).permit(:title, :body)
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<h2>Post a Comment</h2>

<%= form_for([@post, @post.comments.build], remote: true) do |f| %>

  <div class="field">
    <%= f.label :body, 'New Comment:' %><br>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit Your Comment' %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'edit' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', post_comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', post_comment %></td>
        <td><%= link_to 'Edit', edit_post_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', post_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_post_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_comments_path %>

app/views/comments/show.html.erb
<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_post_comment_path(@comment) %> |
<%= link_to 'Back', post_comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
 
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container">
<%= yield %>
</div>

<!-- bottom toolbar nav -->
<br>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Rails</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/posts">Posts</a></li>
        <li class="active"><a href="/users/sign_in">User Sign In</a></li>
      </ul>
    </div>
  </div>
</nav>
<!-- end bottom nav bar -->

<!-- User Account/Auth -->
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<!-- End User Account/Auth -->

<footer>
  <div class="container">
    W.Stout/ECE595/BlogApp
  </div>
</footer>

<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts Listing</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Comments', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div>
<h2>
  <strong>Post Title:</strong>
  <%= @post.title %>
</h2>
</div>


<p>
  <strong>Body:</strong>
  <%= @post.body %><br>
  <small>Updated at: <%= @post.updated_at %> by 
  <strong> <%= User.find(@post.user_id).email %> </strong>
  </small>

</p>

<br>

<div id="comment-list">
  <%= render partial: 'comments/list' %>
</div>

<br>

<div id="comment-form">
  <%= render partial: 'comments/form' %>
</div>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>